trigger:
  branches:
    include: [main]

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: build
        steps:
          # Template desde otro repo (repositorio de templates de la organización)
          - template: templates/docker-build.yml
            parameters:
              imageName: devops-lab
              serviceConnection: acr-connection

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: deploy_dev
        environment: dev          # los "environments" permiten aprobaciones manuales
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploy a dev"
